# Generated by Django 4.2.4 on 2023-08-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='congrats',
        ),
        migrations.RemoveField(
            model_name='post',
            name='saved',
        ),
    ]
